### ISSUE TITLE
protobuff version error

### ISSUE THREAD

**Issue by ajanyan** [palash1992/DynamicGEM#10]
When I run example/example.py,  I am getting the following error.

>[libprotobuf FATAL google/protobuf/stubs/common.cc:61] This program requires
> version 3.6.1 of the Protocol Buffer runtime library, but the installed 
> version is 2.6.1.  Please update your library.  If you compiled the program 
> yourself, make sure that your headers are from the same version of Protocol
> Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/genfiles/tensorflow/core/framework/tensor_shape.pb.cc".)
>terminate called after throwing an instance of 
> 'google::protobuf::FatalException'
>
>  what():  This program requires version 3.6.1 of the Protocol Buffer runtime
> library, but the installed version is 2.6.1.  Please update your library.   If you compiled the program yourself, make sure that your headers are from the
> same version of Protocol Buffers as your link-time library.  (Version 
> verification failed in "bazel-out/k8-opt/genfiles/tensorflow/core/framework
>/tensor_shape.pb.cc".)
>Aborted (core dumped)

My protobuf version in python is:
```
$ pip3 show protobuf
Name: protobuf
Version: 3.6.1
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: None
Author-email: None
License: 3-Clause BSD License
Location: /usr/local/lib/python3.5/dist-packages
Requires: six, setuptools
Required-by: tensorflow, tensorboard, dynamicgem
```

```
$ protoc --version
libprotoc 3.6.1
```
Other details:
```
Operating System : Ubuntu 16.04 LTS
Python 3.5.2
```
I also installed protobuf-cpp-3.6.1

**Comment by Sujit-O** [comment]
We have updated the requirements. The protocol buffer version should be automatically handled while installing the tensorflow now.
