### ISSUE TITLE
broadcast error

### ISSUE THREAD

**Issue by wenjf** [palash1992/DynamicGEM#16]
I tired DynAE DynRNN and DynAERNN today and I found that,
when graphs[i-1] contains only part of nodes of graphs[i], there will be some broadcast error. 
So, does this program requires that each graph contains all the nodes? That's to say, the only differences between them are the edges?

**Comment by Sujit-O** [comment]
Yes, these algorithms are direct encoding methods and are thus transductive, which means that they assume the encoders can see all the nodes.  They focus on capturing the dynamics in terms of changing edges over time to perform link prediction.
