### ISSUE TITLE
What is the difference between  'dynSNDE.py' and 'sdne_dynamic.py'?

### ISSUE THREAD

**Issue by WPZgithub** [palash1992/DynamicGEM#23]
Hello,
I have some questions. What is the difference between  'dynSNDE.py' and 'sdne_dynamic.py'? Which is the implementation of the paper 'Goyal, P., Kamra, N., He, X., & Liu, Y. (2018). DynGEM: Deep Embedding Method for Dynamic Graphs. arXiv preprint arXiv:1805.11273.'? Thanks.

**Comment by palash1992** [comment]
dynSDNE is the implementation DynGEM. sdne_dynamic is a direct dynamic version of SDNE in which you run it multiple times independently on different graphs.
