### ISSUE TITLE
Having problem with 'import scipy.io' after setting DYLD_LIBRARY_PATH on Mac

### ISSUE THREAD

**Issue by dihuang0220** [palash1992/DynamicGEM#4]
Hi,
I am trying to use your library dynamicgem. 

I followed the instructions to set up DynamicGEM. I installed MATLAB Runtime R2017a and set 
export DYLD_LIBRARY_PATH='/Applications/MATLAB/MATLAB_Runtime/v92/runtime/maci64:/Applications/MATLAB/MATLAB_Runtime/v92/sys/os/maci64:/Applications/MATLAB/MATLAB_Runtime/v92/bin/maci64' on Mac.

When I run 'from dynamicgem.utils      import graph_util, plot_util, dataprep_util', I can't import scipy.io properly.

It gave me errors as below:

dlopen(/Users/HuangDi0422/anaconda/lib/python3.5/site-packages/scipy/special/_ufuncs.cpython-35m-darwin.so, 2): Symbol not found: __gfortran_stop_numeric_f08
  Referenced from: /Users/HuangDi0422/anaconda/lib/python3.5/site-packages/scipy/special/_ufuncs.cpython-35m-darwin.so
  Expected in: /Applications/MATLAB/MATLAB_Runtime/v95/sys/os/maci64/libgfortran.3.dylib
 in /Users/HuangDi0422/anaconda/lib/python3.5/site-packages/scipy/special/_ufuncs.cpython-35m-darwin.so

Could you please help me check this problem? Thanks

**Comment by palash1992** [comment]
Hi, were you able to resolve this issue? The library has not been tested on Mac and any input would be appreciated.

**Comment by dihuang0220** [comment]
No, I didn't solve this problem. Still the same error. Thanks

**Comment by palash1992** [comment]
I am closing the issue for now. Once we add compatibility with Mac OS we will revisit this issue.
