### ISSUE TITLE
what does 'lookback' means?

### ISSUE THREAD

**Issue by logomanwolf** [palash1992/DynamicGEM#7]
Hello,
I notice that 'lookback' parameter existed  in dynAE,dynRNN,dynAERNN , but I don't konw what it means.
I set it to 2 , input 10 graphs by timestamp and output 8 embeds as a result.
Do you use two graphs to get an embed?

**Comment by palash1992** [comment]
The above three patterns generate an embedding predictive of the graph at next time step. For this they take the previous "look back" number of graphs and learn the embedding.

**Comment by woaiwodib107** [comment]
@palash1992 When i input a dynamic graph with 10 timestamps and the lookback is 2, the number of the results is 8. Why not the result is 9 (predict 3-11)

**Comment by JackieAnxis** [comment]
@palash1992 Hi sir, I'm just working with your algorithm. I have the problem too. When I set the 'loopback' parameter at 2, will the algorithm work like that (4 time steps input and 3 output predictions)?
![image](https://user-images.githubusercontent.com/19246028/48761458-a2ed6b80-ece3-11e8-8feb-455d4ddaee63.png)

**Comment by palash1992** [comment]
Hi, if the lookback is k, the model uses previous k graphs as input and the current graph as output to understand the dynamic patterns. Thus, if you have 10 graphs and look back 2, it will use graphs 1 and 2 to predict links in graph 3 and graphs 8 and 9 to predict graph 10. The learned parameters can then be used to predict links at time 11 by inputting graphs 9 and 10 but by default, this is not done.

**Comment by logomanwolf** [comment]
Hi,I have some questions. What does it mean if I set 'lookback' to 1? In your paper ,you says lookback can be set to 1 ,but it seems not to make sense. How could we get dynamic information just through one graph?
