### ISSUE TITLE
If lookback is set to 1, what does it mean?

### ISSUE THREAD

**Issue by logomanwolf** [palash1992/DynamicGEM#8]
Hi,I have some questions. What does it mean if I set 'lookback' to 1? In your paper ,you says lookback can be set to 1 ,but it seems not to make sense. How could we get dynamic information just through one graph?

**Comment by palash1992** [comment]
You are right. Lookback of 1 cannot capture dynamic patterns in the graphs. It only uses the previous graph to predict the next one. It boils down to the usual dynamic embedding approaches.
